### ISSUE TITLE
List item UI alignment and scrolling?

### ISSUE THREAD

**Issue by yosun** [sinbad/UnityRecyclingListView#3]
Alignment is off and it doesn't scroll... https://gyazo.com/3266900d6e805a90b8cab60c10111565

**Comment by sinbad** [comment]
You'll have to describe this properly if you want an answer, I'm not clicking on random links I don't recognise.

**Comment by yasirkula** [comment]
@yosun You must set the RecyclingListViewItem's Anchor Min Y, Anchor Max Y and Pivot Y values to 1. This isn't mentioned in the documentation.
